### ISSUE TITLE
Is it convert autio or video to base64?

### ISSUE THREAD

**Issue by ssharmass** [hazemhagrass/phonegap-base64#4]
Hi,
  I want to upload audio and video too so, I am getting issue of not converting in base64 ,please tell me regarding that.

Regards
Shivam

**Comment by roysG** [comment]
yes, also i want to know that.

**Comment by hazemhagrass** [comment]
I'm afraid I'm not understanding you very well, can you post a sample snippet or something?

**Comment by jmbello** [comment]
Hi.
What I think they are talking about is this:
line 83 you have this imgStr = "data:image/*;charset=utf-8;base64," + imgStr;

I'm guessing this only works for image, when i convert some other formats (like audio or video, they use 3gp or mp3/mp4/wav) their mime type will be also data:image.

I have this issue in my project right now, i need to send files (image, audio and video) from my android app to a web server, so, in order to do this i use your plugin to get base64 string and this string convert to blob and finally send it. But when my server receive it cannot convert back to that proper format because of the "hardcoded" mime type.

**Comment by hazemhagrass** [comment]
Sorry for beign too late. Images only are supported
